Repository Lets-JUPJUP/JUPJUP-Back, pull requests merged in 2024-08, with the labels that each got.

#83 feat : 평점 관련 기능을 구현한다.
  src/main/java/efub/back/jupjup/domain/review/controller/ReviewController.java
  src/main/java/efub/back/jupjup/domain/review/domain/Badge.java
  src/main/java/efub/back/jupjup/domain/review/domain/Review.java
  src/main/java/efub/back/jupjup/domain/review/dto/request/ReviewReqDto.java
  src/main/java/efub/back/jupjup/domain/review/dto/response/BadgeInfo.java
  src/main/java/efub/back/jupjup/domain/review/dto/response/Top3BadgeResDto.java
  src/main/java/efub/back/jupjup/domain/review/repository/ReviewRepository.java
  src/main/java/efub/back/jupjup/domain/review/service/ReviewService.java
  src/main/java/efub/back/jupjup/domain/score/controller/ScoreController.java
  src/main/java/efub/back/jupjup/domain/score/domain/AverageScore.java
  src/main/java/efub/back/jupjup/domain/score/domain/Badge.java
  src/main/java/efub/back/jupjup/domain/score/domain/Score.java
  src/main/java/efub/back/jupjup/domain/score/dto/request/ScoreReqDto.java
  src/main/java/efub/back/jupjup/domain/score/exception/AlreadyScoredException.java
  src/main/java/efub/back/jupjup/domain/score/exception/AuthorScoringNotAllowedException.java
  src/main/java/efub/back/jupjup/domain/score/exception/BadgeNotExistsForCodeException.java
  src/main/java/efub/back/jupjup/domain/score/exception/NotValidScoreException.java
  src/main/java/efub/back/jupjup/domain/score/exception/ScoringNotAllowedException.java
  src/main/java/efub/back/jupjup/domain/score/repository/AverageScoreRepository.java
  src/main/java/efub/back/jupjup/domain/score/repository/ScoreRepository.java
  src/main/java/efub/back/jupjup/domain/score/service/ScoreService.java
  src/main/java/efub/back/jupjup/global/exception/ExceptionType.java
  src/main/java/efub/back/jupjup/global/redis/RedisReviewCountService.java
Labels: ✨feat

#85 feat : 쓰레기통 기능 v2 추가
  src/main/java/efub/back/jupjup/domain/admin/trashCan/dto/TrashCanDto.java
  src/main/java/efub/back/jupjup/domain/admin/trashCan/dto/TrashCanSimpleDto.java
  src/main/java/efub/back/jupjup/domain/trashCan/controller/TrashCanController.java
  src/main/java/efub/back/jupjup/domain/trashCan/domain/Feedback.java
  src/main/java/efub/back/jupjup/domain/trashCan/domain/TrashCan.java
  src/main/java/efub/back/jupjup/domain/trashCan/domain/TrashCanType.java
  src/main/java/efub/back/jupjup/domain/trashCan/domain/TrashCategory.java
  src/main/java/efub/back/jupjup/domain/trashCan/service/TrashCanService.java
Labels: 💚backend, ✨feat

#86 Post(플로깅 게시글) 관련 기능 리팩토링을 수행한다.
  src/main/java/efub/back/jupjup/domain/comment/dto/CommentPostDto.java
  src/main/java/efub/back/jupjup/domain/heart/service/HeartService.java
  src/main/java/efub/back/jupjup/domain/post/controller/PostController.java
  src/main/java/efub/back/jupjup/domain/post/domain/District.java
  src/main/java/efub/back/jupjup/domain/post/domain/Post.java
  src/main/java/efub/back/jupjup/domain/post/domain/PostAgeRange.java
  src/main/java/efub/back/jupjup/domain/post/domain/Route.java
  src/main/java/efub/back/jupjup/domain/post/dto/ImageUploadRequestDto.java
  src/main/java/efub/back/jupjup/domain/post/dto/PostRequestDto.java
  src/main/java/efub/back/jupjup/domain/post/dto/PostResponseDto.java
  src/main/java/efub/back/jupjup/domain/post/repository/PostRepository.java
  src/main/java/efub/back/jupjup/domain/post/service/PostService.java
Labels: ✨feat

#87 feat : 플로깅 게시글 필터링 구현
  build.gradle
  src/main/java/efub/back/jupjup/domain/post/controller/PostController.java
  src/main/java/efub/back/jupjup/domain/post/domain/District.java
  src/main/java/efub/back/jupjup/domain/post/dto/PostFilterDto.java
  src/main/java/efub/back/jupjup/domain/post/dto/PostRequestDto.java
  src/main/java/efub/back/jupjup/domain/post/repository/PostRepository.java
  src/main/java/efub/back/jupjup/domain/post/service/PostService.java
  src/main/java/efub/back/jupjup/domain/post/specification/PostSpecification.java
Labels: ✨feat

#88 feat : 쓰레기통 리뷰 중복 방지를 위한 기능 구현
  src/main/java/efub/back/jupjup/domain/trashCan/controller/TrashCanController.java
  src/main/java/efub/back/jupjup/domain/trashCan/domain/Feedback.java
  src/main/java/efub/back/jupjup/domain/trashCan/exception/FeedbackAlreadyExistsException.java
  src/main/java/efub/back/jupjup/domain/trashCan/repository/BinFeedbackRepository.java
  src/main/java/efub/back/jupjup/domain/trashCan/service/TrashCanService.java
  src/main/java/efub/back/jupjup/global/exception/ExceptionType.java
Labels: 💚backend, ✨feat

#89 Heart(북마크), Postjoin(플로깅 참여) 관련 기능 리팩토링을 수행한다.
  src/main/java/efub/back/jupjup/domain/heart/controller/HeartController.java
  src/main/java/efub/back/jupjup/domain/heart/exception/DuplicateHeartException.java
  src/main/java/efub/back/jupjup/domain/heart/service/HeartService.java
  src/main/java/efub/back/jupjup/domain/post/dto/PostResponseDto.java
  src/main/java/efub/back/jupjup/domain/post/service/PostService.java
  src/main/java/efub/back/jupjup/global/exception/ExceptionType.java
Labels: ✨feat, ♻️refactor

#90 feat : 쓰레기통 피드백 업데이트 기능 추가
  src/main/java/efub/back/jupjup/domain/trashCan/domain/BinFeedback.java
  src/main/java/efub/back/jupjup/domain/trashCan/service/TrashCanService.java
Labels: 💚backend, ✨feat

#91 Post(플로깅 게시글) 관련 기능 리팩토링을 수행한다.
  src/main/java/efub/back/jupjup/domain/comment/service/CommentService.java
  src/main/java/efub/back/jupjup/domain/heart/service/HeartService.java
  src/main/java/efub/back/jupjup/domain/post/controller/PostController.java
  src/main/java/efub/back/jupjup/domain/post/repository/PostRepository.java
  src/main/java/efub/back/jupjup/domain/post/service/PostService.java
Labels: 💚backend, ✨feat

#92 feat : 프로필 통계 기능 추가
  src/main/java/efub/back/jupjup/domain/member/controller/MemberController.java
  src/main/java/efub/back/jupjup/domain/member/dto/response/ProfileStatResDto.java
  src/main/java/efub/back/jupjup/domain/member/service/MemberProfileFacade.java
Labels: 💚backend, ✨feat

#94 Post, PostJoin 관련 기능 리팩토링을 수행한다.
  src/main/java/efub/back/jupjup/domain/post/repository/PostRepository.java
  src/main/java/efub/back/jupjup/domain/post/service/PostService.java
  src/main/java/efub/back/jupjup/domain/postjoin/dto/MemberProfileResponseDto.java
  src/main/java/efub/back/jupjup/domain/postjoin/service/PostjoinService.java
Labels: 💚backend, ✨feat

#95 fix : 리뷰(좋아요) 기능 수정
  src/main/java/efub/back/jupjup/domain/userHeart/dto/request/UserHeartReqDto.java
  src/main/java/efub/back/jupjup/domain/userHeart/repository/UserHeartRepository.java
  src/main/java/efub/back/jupjup/domain/userHeart/service/UserHeartService.java
Labels: 💚backend, ✨feat

#96 refactor: 댓글 단 글 조회 응답값 구조 리팩토링
  src/main/java/efub/back/jupjup/domain/comment/service/CommentService.java
Labels: 💚backend, ♻️refactor

#97 refactor: getJoinedPosts 메소드 리팩토링
  src/main/java/efub/back/jupjup/domain/post/service/PostService.java
Labels: 💚backend, ♻️refactor
